### ISSUE TITLE
散歩の記録終了時にメッセージを出す

### ISSUE THREAD

**Issue by azzrhoshino** [AzzSecondaryGroup/WalkRecord#19]
トグルボタン（STOP）押下時に画面の変化が少ないのでToastメッセージを表示する。
メッセージ：散歩の記録を終了しました。散歩履歴一覧から記録内容を確認することができます。

ついでにトグルボタン（START）押下時にもToastメッセージを表示する。
メッセージ：散歩の記録を開始しました。

**Comment by azzmkubota** [comment]
記録開始・記録終了メッセージを表示するよう修正
