### ISSUE TITLE
引き継ぎ

### ISSUE THREAD

**Issue by ykyk3** [AzzSecondaryGroup/WalkRecord#2]
1. githubの編集権限を設定していただきたいです。  
    - 全メンバーに書き込み権限
        - デフォルトをwrightにする設定があるのでそれを設定するのが楽そうです。
    - 星野GLがいない時に設定を変えられるように`owner`等をTLに付与して欲しいです。  
2. 今回の進捗ですが、殆ど開発環境構築や、構築で引っかかる人もいるでしょうから手順書の作成をしていたので開発は着手出来ませんでした。  
3. GitHubにPush出来なかったので、藤山君から構築手順のMDテキストを送付します。  
お手数ですが権限を付与次第連絡いただくかPushをお願いします。  
4. 手順書にAPIキーの設定手順を記載したので、APIキーを取得次第更新お願いします。
5. 以前`gitフロー`とは違う運用方法を検討されていたはずなので、そのフローを明示して頂きたいです(Wiki等)

**Comment by azzrhoshino** [comment]
10月13日作業分や連絡
・DB周りの準備と、ダウンロードしたサンプルをベースに履歴一覧表示部分を作成しています（カロリー計算については領域の確保を目的に設定）
・サンプルではDBからデータを非同期に取得するようになっていて、そこの使い方も確認が必要です。
・アプリリリース用のGoogleアカウントの作成とGoogleMapのKeyを作成。
・SHA1フィンガープリントはひとまず岡江さん分を登録しています。他の人も連絡をもらえたら登録します。
・gitの権限周りなど問題があればまた連絡ください。
・gitの運用方法については、すみませんがまだまとめられていません。ひとまずdevelopから別のブランチを切ってpushした状態で連絡してもらうか、取りまとめ役の人のチェックがあればdevelopにpushしてもらってもよいと思います。
ある程度ベースができるころにはもう少しちゃんとブランチを切って管理したいとは思います。
・動作確認に必要なので、必要なら会社支給のタブレットを各自持ってきてください。
（すでに実機で確認している人もいますが後で実機の確認手順を別途連携します）

**Comment by y-okae** [comment]
11/17作業内容

1.履歴の描画について、ダミーデータから反映されるように修正しました。
2.座標テーブルへのinsert処理を追加しました。
