### ISSUE TITLE
開始時間、終了時間のフォーマット

### ISSUE THREAD

**Issue by azzrhoshino** [AzzSecondaryGroup/WalkRecord#23]
スマホの場合1行に収まらずに折り返してしまうことがあるので表示形式を下記とする
YYYY/MM/DD hh:mmまたはYYYY-MM-DD hh:mm
（0埋めなくてよい）
また、24時間の表記にする。

**Comment by azzmkubota** [comment]
表示形式フォーマットを「YYYY-MM-DD HH:mm」に変更
24時間表記に変更
