### ISSUE TITLE
設定画面の身長の項目追加に伴う修正

### ISSUE THREAD

**Issue by azzrhoshino** [AzzSecondaryGroup/WalkRecord#25]
- [x] 設定画面のレイアウトに身長が追加されているので、入力値を保存/取得できるようにする。
- [x] メイン画面の歩幅を計算している場所で、保存値から身長を取得して計算するようにする。

身長の入力値を保存する処理は、地図表示間隔秒の値をDBに保存している処理にカラム追加して拡張してもよいし、散歩経路描画のダミーモード設定の値を保存する処理を参考にしても構いません。
ダミーモード設定の値保存処理はKey-Value形式でXMLに保存する処理です。
参考：https://qiita.com/YAmi/items/3e5640f365277d70f255
DBへの保存処理を拡張する場合は、そこを実装した甲元君に相談してください。

- [x] 身長の入力値を数値のみ入力可能にする
参考：http://webstation.work/?p=334

- [ ] 身長の入力値の適正範囲チェック処理を追加する（優先度低）
100cm～210cm位

**Comment by watahiki606** [comment]
身長の入力値の適正範囲チェックは未実装です。
