### ISSUE TITLE
メニュー残作業

### ISSUE THREAD

**Issue by azzrhoshino** [AzzSecondaryGroup/WalkRecord#26]
- [x] メニューが正しく出るように修正する
  - [x] お散歩履歴一覧画面（タイトルも表示させる）
  - [x] 設定画面
  - [x] お散歩履歴画面（タイトルをお散歩履歴にする。メニューとタイトルを同じ行にする）
- [x] メニューのetcの項目を削除する
- [x] 設定ページにユーザーが設定する項目を集約することにしたのでカロリー計算用の項目は削除する

**Comment by r-fujiyama** [comment]
ナビゲーションバーに問題があり、すべての画面に付けることができませんでした。
家でやっておきます。

**Comment by y-okae** [comment]
`メニューのetcの項目を削除する`
`設定ページにユーザーが設定する項目を集約することにしたのでカロリー計算用の項目は削除する`
については対応完了しました。

**Comment by r-fujiyama** [comment]
### 対応内容
**content_main.xml**にて**NavigationView**を使用し、ドロワーメニューを実現していた。
同様の方法で横展開しようとしたが、エラー（すみません。詳細を覚えていません。）が発生し表示ができませんでした。
たしか、bar?は２つ使えなないといった旨のエラーだったと思います。

**Comment by azzrhoshino** [comment]
報告では、問題の根本原因が何であるかはできれば書いてほしいです。
（根本原因、それに対してどんな対応を行おうとしたか、解決できそうかがわかればもっと良いです）
先日岡江さんが、詳細画面がメイン画面と同じレイアウトを使用していることが影響しているかもしれないと言っていました。
限られた時間で作業を行わなければならないので、効率の良い実装ではないかもしれませんが、レイアウトを分けて解決できるならそれで解決を目指してほしいです。

**Comment by azzkoumoto** [comment]
@azzrhoshino 
詳細画面と、メイン画面が使い回しになっていることは関係ありません。
この2つの画面には、ツールバーがありますが、他の画面には無いことが直接の原因です。

@r-fujiyama 
ツールバーが置けない理由があったと思いますが、書けますか？

**Comment by r-fujiyama** [comment]
設定画面へはナビゲーションバーを追加しました。
履歴画面へは追加できていません。
履歴画面へナビゲーションバーを追加するには、工夫が必要そうです。
https://stackoverflow.com/questions/31808796/android-how-to-use-toolbar-in-listactivity
https://stackoverflow.com/questions/33857692/how-to-set-a-toolbar-in-a-list-activity/33857770

**Comment by ykyk3** [comment]
@watahiki606 
https://qiita.com/mototakatsu/items/fcbb60458391cbb17710

**Comment by ykyk3** [comment]
@watahiki606 
https://github.com/AzzSecondaryGroup/WalkRecord/commit/ae703fe9dbefb2921cea8b872ac0fff620b1533a

**Comment by ykyk3** [comment]
対応完了のためクローズ
