### ISSUE TITLE
ダミーモードの削除

### ISSUE THREAD

**Issue by ykyk3** [AzzSecondaryGroup/WalkRecord#32]
`build.gladle` にdevelopを設定し、ビルドモード次第で機能を出したりできる様にする。
```
Note:
buildType or productFlavors
```

**Comment by azzkoumoto** [comment]
あまり着手出来ていない。
https://qiita.com/wrbss/items/8213b50f9e2ce6ac87c4

**Comment by azzkoumoto** [comment]
@azzrhoshino 
マイルストーンの使い方サンプルです。
ラベルより、一覧性が良くなりますよ。

**Comment by azzrhoshino** [comment]
@ykyk3 ありがとうございます。マイルストーンの中にIssueを立てるイメージですかね。

**Comment by ykyk3** [comment]
@azzhoshrno
issuesに、マイルストーンを紐付けるだけですよ。
ラベルみたいな使い方です

**Comment by ykyk3** [comment]
@azzrhoshino
issuesに、マイルストーンを紐付けるだけですよ。
ラベルみたいな使い方です

**Comment by azzrhoshino** [comment]
@ykyk3 
理解しました。
ダミーモードは一旦コメントアウトで対応しています。
戻す時は下記を変更
・activity_setting.xmlのSwitchのvisibility⇒visible
・MainActivity.javaのダミーモード設定値取得配下のコメントアウト解除

**Comment by ykyk3** [comment]
@azzrhoshino 
ダミーモードの対応ありがとうございます。
ダミーモードを外す対応を、そこだけでコミットしてもらえれば、`revert`で簡単に取り消す事ができます。

`revert`とは
コミットを打ち消すコミットを作成するコマンドです。
今回の対応であれば、ダミーモードを外すコミットを打ち消すコミットを作るので、お手軽に機能を戻す事ができるようになります。

**Comment by azzrhoshino** [comment]
@ykyk3
すみません。ソース整理してた分と少し混ざってました。
後でデバッグモードを有効にするだけのコミットをしておきますので、不要になったらそれを打ち消すようにお願いします。

**Comment by ykyk3** [comment]
@azzrhoshino 
了解しました！
来週の土曜日の作業にしておきます。
