### ISSUE TITLE
履歴詳細

### ISSUE THREAD

**Issue by azzrhoshino** [AzzSecondaryGroup/WalkRecord#5]
- [x] 地図の描画
    - [x] 履歴一覧から渡された履歴idで履歴テーブルと座標テーブルをselect
    - [x] 座標テーブル1件目の位置で地図を初期表示
    - [x] 座標テーブルの座標の順に線を引く(Polyline)
    - [x] 履歴一覧から取得した情報で散歩情報を表示
        - [x] 開始時間
        - [x] 終了時間
        - [x] 距離
        - [x] 歩数
        - [x] カロリー（優先度低）
- [ ] 地図の拡大、縮小ボタン（優先度低）

**Comment by y-okae** [comment]
ｶﾛﾘｰの実装は、issueの
https://github.com/AzzSecondaryGroup/WalkRecord/issues/36
にて実装しました。
