### ISSUE TITLE
詳細画面描画時にエラー発生することがある

### ISSUE THREAD

**Issue by azzkoumoto** [AzzSecondaryGroup/WalkRecord#8]
一覧画面に表示される最初の履歴は今の所100%座標が取得できなくてぬるぽで落ちている。
２件目以降は取れているのでinsert出来ていなさそう

回避策
２件目以降で描画できるのでとりあえずは問題なし

**Comment by azzrhoshino** [comment]
一覧タップ時に取得していたidが履歴テーブルのidとは異なっていた。

タップ時に取得できるposition値（0開始の履歴一覧の行番号）を使用するように変更する。
ListView作成時に取得していた履歴テーブルListからpositionを使用して、タップした散歩情報を取得し、履歴idを詳細画面に渡すように変更。

**Comment by azzrhoshino** [comment]
対応内容マージ済
