### ISSUE TITLE
権限ない状態から startボタン 実行するとエラー

### ISSUE THREAD

**Issue by azzkoumoto** [AzzSecondaryGroup/WalkRecord#9]
アプリインストールして初めてstartボタンを押すと、ファイル書き込み権限の確認ダイアログ表示と同時に落ちる
多分OKする前に書き込もうとしている？

回避策
回避は出来ないが、ダイアログは残るので権限を与えてから再起動すれば以降問題なく動く

**Comment by azzrhoshino** [comment]
書き込み権限はなくしたので多分もう起きないと思います。念のためテストで問題ないことを確認してクローズ
